### ISSUE TITLE
BLE Service Error BLE Scan Fail

### ISSUE THREAD

**Issue by Leighlees** [Semper-Viventem/MetaRadar#106]
**Describe the bug**
Scan feature no longer works, scan fails

**To Reproduce**
1. Open the app
2. Click on 'Scan'
3. No results show
4. Click on Journal tab
5. Service Errors appear multiple times

**Expected behavior**
Scan works and devices show

**Screenshots**
![Screenshot_20240209-091712](https://github.com/Semper-Viventem/MetaRadar/assets/159494652/049cf78c-2545-4afb-914d-8188347a547e)
![Screenshot_20240209-091650](https://github.com/Semper-Viventem/MetaRadar/assets/159494652/d0865997-6273-4fb9-a6cf-9d1becc3c2be)

**Smartphone (please complete the following information):**
 - Device: Motorola Razr 40 ultra
 - OS: Android 13
 - Browser: Chrome 
 

**Additional context**
Was working perfectly to behind with. First error message ever was that Bluetooth was off.

Had profile detection once after that, then multiple error code 2. Profile detections once a day for next 3 days but nothing but error code 2 since. Scan just worked in the background, does not run anymore.

Have cleared out garbage and backed up.

Have not yet reinstalled app.

**Comment by Semper-Viventem** [comment]
Hey, oh it looks like the issue I know. Could you try to reboot your phone and check if the issue is still appearing?

**Comment by Leighlees** [comment]
> Hey, .oh it looks like the issue I know. Could you try to reboot your phone and check if the issue is still appearing?

Interesting, I had done this a couple of times with no success, but it has reset something this time as it appears to be scanning now. Thank you

**Comment by Semper-Viventem** [comment]
Good to hear it has helped. This issue is mostly related to the Android platform logic but not the app itself. Android has a limit of 32 active registered BLE adapters across all apps and some apps might utilize the whole BLE resources (it might be even the system itself) and don't clear the adapter. The only possible solution is to relaunch the device, unfortunately.
