### ISSUE TITLE
[Feature Request] Search for "By manufacturer"

### ISSUE THREAD

**Issue by Dtrieb** [Semper-Viventem/MetaRadar#109]
Give us the possibility to search for a manufacturer by entering charts.

Only scroll through the list is terrible.

![Screenshot_20240210-223355](https://github.com/Semper-Viventem/MetaRadar/assets/3650284/80569722-f84b-442b-b771-08cb1ef253f2)

**Comment by Semper-Viventem** [comment]
Agree. Added a search field since version `22.8-beta`
