### ISSUE TITLE
[Feature Request] Give an option to disable map

### ISSUE THREAD

**Issue by stanley211** [Semper-Viventem/MetaRadar#112]
Please give an option to disable this app its maps feature. It slows down my phone, and it might have privacy issues. 

Note:
(I have a galaxy A53 5G 6GB RAM with 2GB turn on of the Samsung swap like ram on the internal storage.) I'm not sure if it is the culprit.

**Comment by Semper-Viventem** [comment]
Could you specify why you found this a possible privacy issue?

I don't think it is possible to easily disable the map because some functionality will be lost: `location history on the device details screen` and `find by location` radar profile filter. I'll consider if it is possible to do it with little blood but I cannot promise.

**Comment by stanley211** [comment]
Just know, when a first-party, that is this app, uses a third party like the map features, the first party have no ways to prevent other third safety security. I use a no-root firewall, your app constanly retrieving maps from the map company. The thrird company maps usully can changed its Privacy Policies any time its wants. Those caused privacy issues.

**Comment by stanley211** [comment]
I understand, like when walking outside  other can view you. An example like the webserver they hosting on or the user device ISP have eyes too.

On February 19, 2024 11:10:17 AM EST, Konstantin Kulikov ***@***.***> wrote:
>I use OpenStreetMaps, which is fully open-source and doesn't store any data from the map clients.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/Semper-Viventem/MetaRadar/issues/112#issuecomment-1952785479
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
Stanley

Stanley Compere
***@***.***

**Comment by Semper-Viventem** [comment]
> I understand, like when walking outside  other can view you. An example like the webserver they hosting on or the user device ISP have eyes too.

Map obtains information only when the map view is presented on the screen. There should be no networking when the app is in the background. But I totally agree with you, it should be an option to disable any network connection for the app. I'll investigate how to implement this.

**Comment by stanley211** [comment]
An example of what I'm talking about, by using tracert and traceroute linux commands. You'll see other things are  always viewing you online regardless if you using security tools.

On February 20, 2024 10:33:31 AM EST, Stanley ***@***.***> wrote:
>I understand, like when walking outside  other can view you. An example like the webserver they hosting on or the user device ISP have eyes too.
>
>On February 19, 2024 11:10:17 AM EST, Konstantin Kulikov ***@***.***> wrote:
>>I use OpenStreetMaps, which is fully open-source and doesn't store any data from the map clients.
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/Semper-Viventem/MetaRadar/issues/112#issuecomment-1952785479
>>You are receiving this because you modified the open/close state.
>>
>>Message ID: ***@***.***>
>Stanley
>
>Stanley Compere
>***@***.***
Stanley

Stanley Compere
***@***.***

**Comment by stanley211** [comment]
Just look how most Camera app that came with most phone can do GPS thag a photo. with such tags it is possible to know where that picture was taken. The Camera app usually ask the first time the opening if its user wants such option enable or gave an option to disable or enable in the setting. And please also avoids using named brands in publics messages. May a disclaimer in the app might be a good idea too.

On February 21, 2024 10:02:44 AM EST, Stanley ***@***.***> wrote:
>I recommend one offline and one online, if it not too stressful for you. I have seen other app in f-droid do this. Since this is a featute request, and not a bug, you dont't have to wasted time on me. It is just a month of this app, might equals high usage datas drain.
>
>On February 20, 2024 12:20:23 PM EST, Konstantin Kulikov ***@***.***> wrote:
>>> I understand, like when walking outside  other can view you. An example like the webserver they hosting on or the user device ISP have eyes too.
>>
>>Map obtains information only when the map view is presented on the screen. There should be no networking when the app is in the background. But I totally agree with you, it should be an option to disable any network connection for the app. I'll investigate how to implement this.
>>
>>-- 
>>Reply to this email directly or view it on GitHub:
>>https://github.com/Semper-Viventem/MetaRadar/issues/112#issuecomment-1954686284
>>You are receiving this because you modified the open/close state.
>>
>>Message ID: ***@***.***>
>Stanley
>
>Stanley Compere
>***@***.***
Stanley

Stanley Compere
***@***.***

**Comment by Semper-Viventem** [comment]
I implemented `Offline mode` for the app. In this mode all network communications will be disabled the map will be turned off. You should enable this mode in the app settings. For F-Droid builds offline mode will be enabled by default. The functionality is available since the app version `23.0-beta`. The app build will be available in GitHub in a few hours, in G-Play tomorrow and I hope in F-Droid in a few weeks.

I don't see any reason to do a separate app build without internet permission and publish it separately. Especially for F-Droid, because the F-Droid publishing process is fucking annoying. Hope the offline mode will be enough and everybody can check the app network activity via profiler or system analysis if you want to be sure the offline mode works.
