### ISSUE TITLE
won't take a complement. 

### ISSUE THREAD

**Issue by CW420** [Semper-Viventem/MetaRadar#129]
**Describe the bug**
So I gave this app a star on github and 5 stars on Google,  but it immediately asked me to rate it again. Witch you can't really do. It now opens and asks every time I run the app :(.

**To Reproduce**
Nothing immediately 
Opted to report as bug

**Expected behavior**
To stop asking, it us worse then my ex wife, dose this make my a.... you get the idea. Nothing I do or say ends it.

**Screenshots**
No I am lazy and you don't need to see what other apps I am running.
(Lazy)

**Smartphone (please complete the following information):**
 - latest android as of 4/16/24
 - current version of the app from Play Store.
 - Hardware is GalaxyS23 U. 

**Additional context**
Out side of it not knowing how to let go of the fact I have already rated it and had given it a standing ovation, it's been fine.

**Comment by Semper-Viventem** [comment]
Oh, I'm sorry about that. The app doesn't know if you gave some review in Google Play or Github, it just checks if you clicked any of the buttons in the "Rate me" dialogue.
