### ISSUE TITLE
Wild card support in radar profiles

### ISSUE THREAD

**Issue by ajcates** [Semper-Viventem/MetaRadar#130]
I'm always frustrated when the police wearing there Axon body cameras sneak up on me.

**Describe the solution you'd like**
![Screenshot_20240424-104256_BLE Radar](https://github.com/Semper-Viventem/MetaRadar/assets/233872/a4c80c9c-364e-4299-a50c-f172ba4a8f6e)

**Describe alternatives you've considered*
A clear and concise description of any alternative.

My [Tasker profile for detection of the police](https://taskernet.com/shares/?user=AS35m8lxYIrMKBf7zGlrfe91ixZnsiBVcSDVAgyc4atbA9BY1fOimBj9rvs4OiGnOVsPuz%2Fn&id=Profile%3APolice+Scanner) which works surprisingly well for me.

**Comment by Semper-Viventem** [comment]
Good idea. I think it should be not a placeholder but a regular expression. Added since the `0.25.0-beta` version. In case of a regex, your address should be like `00:25:DF:..:..:..` or just `00:25:DF:`.

Please don't use the app for anything illegal.
