### ISSUE TITLE
Regex in regular search

### ISSUE THREAD

**Issue by ajcates** [Semper-Viventem/MetaRadar#135]
I'm always frustrated when I try and use regex search in the regular search panel and it doesn't work.

The solution is to implement regex searching in the default search box on the main page.

![Screenshot_20240428-124331_BLE Radar](https://github.com/Semper-Viventem/MetaRadar/assets/233872/f4aaf965-19ac-478b-b242-bcf7af9f3652)

Also thank you for adding regex in the radar profiles.

**Comment by Semper-Viventem** [comment]
Supported in `0.25.2-beta`
