### ISSUE TITLE
0.. 00. Wha?  Please read. 

### ISSUE THREAD

**Issue by afreaknlife** [Semper-Viventem/MetaRadar#158]
Feature Request would be a description available of what kind of signal device it is, a brief statement of it's purpose, and how close to us it is.  Anything that would help a person in an observed position, no matter what side they're on.  HahahAA, Git sum. 

I don't have time to have tried other options.  This is like "SAIL," MoFo's!  Correctamundo.   I need help.  I also need something that has to do with energy beams that influence hallucinations and or thought patterns. Something that negates that. That's a whole 'nother app.  That would help me know which things are reality and which things are psychic vision and which things are influenced by frequencies.  

No, seriously.
🌌 Debboriah 🔮🦋🪖♾️

**Comment by Semper-Viventem** [comment]
Lol, what? Yah the device type would be nice to do.
