### ISSUE TITLE
The app is crashing

### ISSUE THREAD

**Issue by userkilled** [Semper-Viventem/MetaRadar#28]
It absolutely crashes when you press the 'scan' button if one of the interfaces needed by the application is turned off. And always asks for access to the location if 'permission during use'

**Comment by Semper-Viventem** [comment]
> App crashes if one of the interfaces is turned off

Could you specify the app version? There were a few fixes regarding this behavior today.

<br>

> Always asks for location even if `permission during use` is granted

The app scans BLE in the background, so the background location access is necessary for correct service working

**Comment by userkilled** [comment]
0.4 alfa


Okay, I'll keep that in mind.
Thanks. Probably should tell the location to be in any mode. 

Oh, that's right, after reading normally I saw that from all sources.

**Comment by userkilled** [comment]
Я продублировал, выходит. Извините

**Comment by userkilled** [comment]
Только что обновил, всё прекрасно ☕

**Comment by Semper-Viventem** [comment]
Класс, все равно спасибо за репорт!
