### ISSUE TITLE
Feature request- Add option to ignore devices like smart watches or Bluetooth in car

### ISSUE THREAD

**Issue by spart0n654** [Semper-Viventem/MetaRadar#33]
I have several devices in my car plus my smart watch I'd like to ignore and only be notified of other ones

**Comment by Semper-Viventem** [comment]
Hello, why current filters are not enough in your case?

![image](https://user-images.githubusercontent.com/18288554/223291374-47ed2eb0-95a4-41e0-818c-2468e9de12e4.png)

**Comment by spart0n654** [comment]
Gotcha! I didn't dig deep enough into the filters I'm sorry.

**Comment by Semper-Viventem** [comment]
That's fine, it looks like I need to make this more clear. Thank you for the report, I'll add a more easy way to add some devices to the exclusions
