### ISSUE TITLE
dark mode please 🙏 

### ISSUE THREAD

**Issue by robertogogoni** [Semper-Viventem/MetaRadar#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Semper-Viventem** [comment]
The first iteration of Dark Mode is done and should be available since version `0.20.0-beta`

<img src="https://github.com/Semper-Viventem/MetaRadar/assets/18288554/e42b6067-b1b8-47da-9bb7-ddc32aa4a171" width=300 />
