### ISSUE TITLE
Taging and Renaming of Devices 

### ISSUE THREAD

**Issue by VarunBatraIT** [Semper-Viventem/MetaRadar#43]
Can you please add a tag and rename the device?  I want to tag some devices as home, office , car and I also want to rename some devices to more rememberable like Office TV

**Comment by Semper-Viventem** [comment]
Hey, that's a really good idea, I just decided to implement this a few days ago because I also faced such a problem. Technically, it's implemented at the data layer and waiting for UI implementation!

**Comment by Semper-Viventem** [comment]
Hey,
Device tags will be available since app version `0.17-beta`. I'm not sure about custom names but will add a comment field in the future.

https://github.com/Semper-Viventem/MetaRadar/pull/45
