### ISSUE TITLE
Error then scanning

### ISSUE THREAD

**Issue by edkodz** [Semper-Viventem/MetaRadar#50]
**Describe the bug**
BLE scan fail with error: 2

**Expected behavior**
Scan in backgroud.

**Screenshots**

![Screenshot_20230503-055656](https://user-images.githubusercontent.com/67428184/235825995-a2b3abd6-8ac9-489a-bbc2-518b6aa51a32.png)

**Smartphone (please complete the following information):**
 - Device: sony xperia 1 iii
 - OS: android 13

**Comment by Semper-Viventem** [comment]
The issue should be fixed for now
