### ISSUE TITLE
[Feature Request] Be in F-Droid

### ISSUE THREAD

**Issue by marek22k** [Semper-Viventem/MetaRadar#56]
Hello,

F-Droid is an app store that delivers only FLOSS apps. It builds the apps itself. On some operating systems without Google in F-Droid the only app store.

Currently BLE Radar is unfortunately only available through IzzyOnDroid or Obtainium.

**Comment by Semper-Viventem** [comment]
Hey, thank you. Created a request to be listed in F-Droid

https://gitlab.com/fdroid/rfp/-/issues/2506
