### ISSUE TITLE
[Feature request] Add distance between smartphone and BLE Device

### ISSUE THREAD

**Issue by Dtrieb** [Semper-Viventem/MetaRadar#71]
Please add the distance between smartphone and BLE Device during the scan.

**Comment by Semper-Viventem** [comment]
Hey, I'm working on the improvement of the Scanning Mode to make a better representation of the trackable devices around at the present moment. It should include signal range and approximate distance as well. Stay in the touch

**Comment by Semper-Viventem** [comment]
The active scanner mode has been implemented and available since `0.22.1-beta`. It contains distance and signal range but notice that distance is approximate
